# Generated by Django 6.0.6 on 2026-06-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(max_length=14)),
                ('nascimento', models.DateField(max_length=20)),
                ('curso', models.CharField(max_length=14)),
                ('turma', models.CharField(max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
