# Generated by Django 6.0.6 on 2026-06-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_alter_alunos_options_alter_alunos_nascimento_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='idade',
        ),
    ]
