# Generated by Django 6.0.6 on 2026-06-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_remove_alunos_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='idade',
            field=models.CharField(default=18, max_length=14),
            preserve_default=False,
        ),
    ]
