# Generated by Django 6.0.6 on 2026-06-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0005_alunos_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='idade',
            field=models.IntegerField(default=0),
        ),
    ]
