# Generated by Django 6.0.6 on 2026-06-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_alter_alunos_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=20)),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.alunos')),
            ],
        ),
    ]
