# Generated by Django 6.0.6 on 2026-06-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0007_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cpf',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alunos',
            name='curso',
            field=models.CharField(max_length=100),
        ),
    ]
