# Generated by Django 6.0.6 on 2026-06-12 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0008_conta_cpf_alter_alunos_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campus'},
        ),
        migrations.RemoveField(
            model_name='campus',
            name='alunos',
        ),
        migrations.AddField(
            model_name='alunos',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desafio.campus'),
        ),
    ]
